local addonName, ns = ...
local R = _G.ReduxUI
local AB = R.Modules.ActionBars
local L = R.L

AB.UPDATE_DEFAULT_MODE = { [""] = "Never", ANY_CLICK = "Any Click", LEFT_CLICK = "Left Click", RIGHT_CLICK = "Right Click", MIDDLE_CLICK = "Middle Click" }
AB.COLUMN_DIRECTIONS = { "Right", "Left" }
AB.ROW_DIRECTIONS = { "Up", "Down" }
AB.FLYOUT_DIRECTIONS = { "UP", "DOWN", "LEFT", "RIGHT" }
AB.OUT_OF_RANGE_COLORING = { "button", "hotkey" }
AB.DEFAULT_COOLDOWN_LABELS = { 5, 15, 30, 60, 120, 180, 300 }
AB.COOLDOWN_FILTERS = { NONE = "NONE" }
AB.Styles = { Vanilla = "Vanilla", Modern = "Modern" }

local DEFAULT_BUTTON_CONFIG = {
    size = 36,
    type = "ACTIONBUTTON",
    clickOnDown = true,
    checkSelfCast = true,
    checkFocusCast = true,
    checkMouseoverCast = true,
    flyoutDirection = "UP",
    outOfRangeColoring = "button",
    keybindFont = R.media.defaultFont,
    keybindFontSize = 11,
    keybindFontOutline = "OUTLINE",
    keybindFontShadow = false,
    hideKeybindText = false,
    countFont = R.media.defaultFont,
    countFontSize = 11,
    countFontOutline = "OUTLINE",
    countFontShadow = false,
    macroFont = R.media.defaultFont,
    macroFontSize = 11,
    macroFontOutline = "OUTLINE",
    macroFontShadow = false,
    hideMacroText = true
}

R:RegisterModuleConfig(AB, {
    enabled = true,
    statusbars = { experience = R.Libs.SharedMedia:Fetch("statusbar", "Redux"), reputation = R.Libs.SharedMedia:Fetch("statusbar", "Redux") },
    microButtonAndBags = { enabled = true, point = { "BOTTOMRIGHT", "BOTTOMRIGHT", 0, 0 }, fader = R.config.faders.mouseOver },
    actionBar1 = {
        enabled = true,
        page = 1,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 50 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 12,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = true,
        border = true,
        shadow = true,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "ACTIONBUTTON" }),
        pageButtonStyle = AB.Styles.Modern,
        modernArt = { enabled = false },
        vanillaArt = { enabled = true, stackBottomBars = false }
    },
    actionBar2 = {
        enabled = true,
        page = 6,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 90 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 12,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR1BUTTON" })
    },
    actionBar3 = {
        enabled = true,
        page = 5,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 128 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 12,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR2BUTTON" })
    },
    actionBar4 = {
        enabled = true,
        page = 3,
        point = { "RIGHT", "UIParent", "RIGHT", -5, 0 },
        fader = R.config.faders.mouseOver,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 1,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR3BUTTON", flyoutDirection = "LEFT" })
    },
    actionBar5 = {
        enabled = true,
        page = 4,
        point = { "RIGHT", "UIParent", "RIGHT", -43, 0 },
        fader = R.config.faders.mouseOver,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 1,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR4BUTTON", flyoutDirection = "LEFT" })
    },
    actionBar6 = {
        enabled = false,
        page = 7,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 5 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 6,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR5BUTTON" })
    },
    actionBar7 = {
        enabled = false,
        page = 8,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 5 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 6,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR6BUTTON" })
    },
    actionBar8 = {
        enabled = false,
        page = 9,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 5 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 6,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR7BUTTON" })
    },
    actionBar9 = {
        enabled = false,
        page = 10,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 5 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 6,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR8BUTTON" })
    },
    actionBar10 = {
        enabled = false,
        page = 11,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 5 },
        fader = R.config.faders.onShow,
        columnDirection = "Right",
        rowDirection = "Down",
        buttons = 12,
        buttonsPerRow = 6,
        columnSpacing = 2,
        rowSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "MULTIACTIONBAR9BUTTON" })
    },
    stanceBar = {
        enabled = true,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 169 },
        fader = R.config.faders.onShow,
        columnSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = false,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "SHAPESHIFTBUTTON", size = 32 })
    },
    petBar = {
        enabled = true,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 169 },
        fader = R.config.faders.onShow,
        columnSpacing = 2,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        showGrid = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { type = "BONUSACTIONBUTTON", size = 32 })
    },
    vehicleExitBar = {
        enabled = true,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 220 },
        fader = R.config.faders.onShow,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { size = 32 })
    },
    totemBar = {
        enabled = true,
        point = { "BOTTOM", "UIParent", "BOTTOM", 0, 169 },
        fader = R.config.faders.onShow,
        columnSpacing = 5,
        backdrop = false,
        border = false,
        shadow = false,
        locked = true,
        buttonStyle = R:CopyTable(DEFAULT_BUTTON_CONFIG, { size = 32 }),
        colors = { EARTH = { 0.16, 0.47, 0, 1 }, FIRE = { 0.65, 0.21, 0, 1 }, WATER = { 0.13, 0.49, 0.67, 1 }, AIR = { 0.45, 0, 0.74, 1 }, SUMMON = { 0.33, 0.2, 0, 1 }, RECALL = { 0.33, 0.2, 0, 1 } }
    },
    extraActionBar = { enabled = true, point = { "BOTTOM", "UIParent", "BOTTOM", 0, 305 }, fader = R.config.faders.onShow },
    zoneBar = { enabled = true, point = { "BOTTOM", "UIParent", "BOTTOM", 0, 225 }, fader = R.config.faders.onShow },
    experienceBar = { enabled = true, point = { "BOTTOM", "UIParent", "BOTTOM", 0, 25 }, size = { 452, 12 }, backdrop = true, border = true, shadow = true },
    statusTrackingBar = { enabled = true, point = { "BOTTOM", "UIParent", "BOTTOM", 0, 8 }, size = { 452, 12 }, backdrop = true, border = true, shadow = true },
    systemInfo = {
        enabled = true,
        lowLatencyTreshold = 70,
        lowLatencyColor = { 0 / 255, 175 / 255, 0 / 255 },
        mediumLatencyTreshold = 120,
        mediumLatencyColor = { 225 / 255, 150 / 255, 0 / 255 },
        highLatencyColor = { 225 / 255, 0 / 255, 0 / 255 },
        lowFpsTreshold = 20,
        lowFpsColor = { 225 / 255, 0 / 255, 0 / 255 },
        mediumFpsTreshold = 50,
        mediumFpsColor = { 225 / 255, 150 / 255, 0 / 255 },
        highFpsColor = { 0 / 255, 175 / 255, 0 / 255 },
        addonsToDisplay = 10
    }
})
